# Generated by Django 5.2.4 on 2025-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('type', models.CharField(choices=[('Journal', 'Journal'), ('Life updates', 'Live updates'), ('Travel', 'Travel'), ('Personal development', 'Personal development'), ('IT', 'IT')], default='Journal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.BooleanField(default=True)),
            ],
        ),
    ]
